language: go
go:
- master
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- go get github.com/tools/godep
script:
- go install
- CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o fbarrel-linux-amd64
  .
deploy:
  provider: releases
  api_key:
    secure: S9NToZ+o61G6/YN2C7wSvmRbgTmFBhIdpZB1RSAELy/wbp/VCfrDo/831SQYGw9znZjOIevcmZqbe7+Q1qp0zV6w+gJxdSvUDKjmJJh1KbkArlWMe/QfD1fmUPK7oKKlsvxWTz2YG5sS65iCIiHheIaf/GwBUC3Pu9jR7uxkxjtxlBzZTs+06QKIbXeTFv56jLCbac5Nc7Oo5n+ySV9eYc6hyK5nBnpaWn8gPzZ18UZJaTdBeWlT19DfWrKnQovAZZBxRlNvfzlLUXusP7ajRjuIk4VPOge54tMx4SYkpImhaJL+F1RWCRB7LxfbabxIDHwCZ61MqmLB3CnuR12zwQuWHRBBfbaP7Pc5gUi/3vYc6xtEgCMBWh/t5VHNi/6RiuVLnwPwGLbA6arsm+zObxwlWuzXxcXZYpfcq8OpDxDp/YwG8CGLYlNzXkmFPn7sNjy5jQ7eD9w877bw7pEph2W3Fl6o5Iva9zDEbPLNHcAP9aIjPib/snq/InF0lxyQDTaPork9fDUg4Yyva9D+3Fwi+DbwDxT3RpFju5tKTpFOuoEADI+5i1fPZRPYJMnapFLP6CIR8wExRURxYr/5wfBVWErMYYk1e1S64rhanWhFmA9lxl0l7M48ORBseJavtML252OP3flIoFpKQ6bvsaOASuA5CDPnS6WrQZ3PWcw=
  file: fbarrel-linux-amd64
  on:
    repo: brocode/fbarrel
